[package]
name = "one_test"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
clap = { version = "4.5.4", features = ["derive"] }
rexpect = "0.5.0"
ron = "0.8.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.115"
